from pathlib import Path
path = Path('src/App.tsx')
lines = path.read_text().splitlines(True)

# Patch search block for createRecruitment payload logic
start = next(i for i, line in enumerate(lines) if line.strip() == 'const selectedSlot =' and 'selectedRecruitTimeMode' in lines[i+1])
end = next(i for i, line in enumerate(lines[start:], start) if line.strip().startswith('const joinRecruitment = async'))
new_block = [
    '    const selectedSlot =\n',
    '      selectedRecruitTimeMode === "preset"\n',
    '        ? {\n',
    '            day: BREAK_TIME_SLOTS.find((slot) => slot.id === selectedRecruitPresetSlotId)?.label || BREAK_TIME_SLOTS[0].label,\n',
    '            start: BREAK_TIME_SLOTS.find((slot) => slot.id === selectedRecruitPresetSlotId)?.start || BREAK_TIME_SLOTS[0].start,\n',
    '            end: BREAK_TIME_SLOTS.find((slot) => slot.id === selectedRecruitPresetSlotId)?.end || BREAK_TIME_SLOTS[0].end,\n',
    '          }\n',
    '        : { day: customRecruitDay, start: customRecruitStart, end: customRecruitEnd };\n',
    '    const game = selectedRecruitGame || customRecruitGame || "募集ゲーム";\n',
    '    const payload = {\n',
    '      ownerId: owner.id,\n',
    '      slot: selectedSlot,\n',
    '      game,\n',
    '      capacity: room.capacity || 4,\n',
    '    };\n',
    '    if (customRecruitRoom.trim()) {\n',
    '      payload.roomName = customRecruitRoom.trim();\n',
    '    } else {\n',
    '      payload.roomId = room.id;\n',
    '    }\n',
    '\n',
    '    setLoading(true);\n',
    '    try {\n',
    '      await api.createRecruitment(payload);\n',
    '      setStatusMessage("募集を作成しました。");\n',
    '      await refreshAll();\n',
    '    } catch (error) {\n',
    '      setStatusMessage(`募集作成エラー: ${error}`);\n',
    '    } finally {\n',
    '      setLoading(false);\n',
    '    }\n',
]
lines[start:end] = new_block

# Patch recruitment card UI block
ui_start = next(i for i, line in enumerate(lines) if line.strip() == '<div className="card">' and i+1 < len(lines) and '募集を作成' in lines[i+1])
ui_end = next(i for i, line in enumerate(lines[ui_start:], ui_start) if line.strip() == '<div>' and i+1 < len(lines) and lines[i+1].strip() == '<h3>募集中の募集</h3>')
new_ui = [
    '            <div className="card">\n',
    '              <div className="card-title">募集を作成</div>\n',
    '              <div\n',
    '                style={{\n',
    '                  display: "grid",\n',
    '                  gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",\n',
    '                  gap: "16px",\n',
    '                  alignItems: "start",\n',
    '                }}\n',
    '              >\n',
    '                <div className="card-field" style={{ flexDirection: "column" }}>\n',
    '                  <span className="card-label">募集者</span>\n',
    '                  <select\n',
    '                    value={selectedRecruitOwner}\n',
    '                    onChange={(event) => setSelectedRecruitOwner(event.target.value)}\n',
    '                    disabled={users.length === 0}\n',
    '                  >\n',
    '                    {users.map((user) => (\n',
    '                      <option key={user.id} value={user.id}>\n',
    '                        {user.nickname}\n',
    '                      </option>\n',
    '                    ))}\n',
    '                  </select>\n',
    '                </div>\n',
    '                <div className="card-field" style={{ flexDirection: "column" }}>\n',
    '                  <span className="card-label">教室</span>\n',
    '                  <input\n',
    '                    type="text"\n',
    '                    value={customRecruitRoom}\n',
    '                    onChange={(event) => setCustomRecruitRoom(event.target.value)}\n',
    '                    placeholder="ここに教室名を入力"\n',
    '                    style={{ width: "100%" }}\n',
    '                  />\n',
    '                  <span style={{ margin: "8px 0 4px 0", color: "#555" }}>または既存教室を選択</span>\n',
    '                  <select\n',
    '                    value={selectedRecruitRoom}\n',
    '                    onChange={(event) => setSelectedRecruitRoom(event.target.value)}\n',
    '                    disabled={rooms.length === 0}\n',
    '                  >\n',
    '                    {rooms.map((room) => (\n',
    '                      <option key={room.id} value={room.id}>\n',
    '                        {room.name} ({room.building})\n',
    '                      </option>\n',
    '                    ))}\n',
    '                  </select>\n',
    '                </div>\n',
    '                <div className="card-field" style={{ flexDirection: "column" }}>\n',
    '                  <span className="card-label">時間</span>\n',
    '                  <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>\n',
    '                    <button\n',
    '                      type="button"\n',
    '                      className={`button-chip ${selectedRecruitTimeMode === "preset" ? "selected" : ""}`}\n',
    '                      onClick={() => setSelectedRecruitTimeMode("preset")}\n',
    '                    >\n',
    '                      リストから選択\n',
    '                    </button>\n',
    '                    <button\n',
    '                      type="button"\n',
    '                      className={`button-chip ${selectedRecruitTimeMode === "custom" ? "selected" : ""}`}\n',
    '                      onClick={() => setSelectedRecruitTimeMode("custom")}\n',
    '                    >\n',
    '                      カスタム入力\n',
    '                    </button>\n',
    '                  </div>\n',
    '                  {selectedRecruitTimeMode === "preset" ? (\n',
    '                    <select\n',
    '                      value={selectedRecruitPresetSlotId}\n',
    '                      onChange={(event) => setSelectedRecruitPresetSlotId(event.target.value)}\n',
    '                      style={{ marginTop: "8px" }}\n',
    '                    >\n',
    '                      {BREAK_TIME_SLOTS.map((slot) => (\n',
    '                        <option key={slot.id} value={slot.id}>\n',
    '                          {slot.label} ({slot.start} - {slot.end})\n',
    '                        </option>\n',
    '                      ))}\n',
    '                    </select>\n',
    '                  ) : (\n',
    '                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px", marginTop: "8px" }}>\n',
    '                      <label style={{ display: "flex", flexDirection: "column", gap: "4px" }}>\n',
    '                        曜日\n',
    '                        <select value={customRecruitDay} onChange={(event) => setCustomRecruitDay(event.target.value)}>\n',
    '                          {DAYS.map((day) => (\n',
    '                            <option key={day.id} value={day.id}>\n',
    '                              {day.label}\n',
    '                            </option>\n',
    '                          ))}\n',
    '                        </select>\n',
    '                      </label>\n',
    '                      <label style={{ display: "flex", flexDirection: "column", gap: "4px" }}>\n',
    '                        開始\n',
    '                        <input\n',
    '                          type="time"\n',
    '                          value={customRecruitStart}\n',
    '                          onChange={(event) => setCustomRecruitStart(event.target.value)}\n',
    '                        />\n',
    '                      </label>\n',
    '                      <label style={{ display: "flex", flexDirection: "column", gap: "4px" }}>\n',
    '                        終了\n',
    '                        <input\n',
    '                          type="time"\n',
    '                          value={customRecruitEnd}\n',
    '                          onChange={(event) => setCustomRecruitEnd(event.target.value)}\n',
    '                        />\n',
    '                      </label>\n',
    '                    </div>\n',
    '                  )}\n',
    '                </div>\n',
    '                <div className="card-field" style={{ flexDirection: "column" }}>\n',
    '                  <span className="card-label">やりたいこと</span>\n',
    '                  <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", alignItems: "center" }}>\n',
    '                    <span style={{ flex: 1, minWidth: 0, color: "#4b362d" }}>\n',
    '                      {selectedRecruitGame || customRecruitGame || "未選択"}\n',
    '                    </span>\n',
    '                    <button\n',
    '                      type="button"\n',
    '                      className="button-chip small"\n',
    '                      onClick={() => setIsRecruitGameOpen((prev) => !prev)}\n',
    '                    >\n',
    '                      {isRecruitGameOpen ? "閉じる" : "選択"}\n',
    '                    </button>\n',
    '                  </div>\n',
    '                  {isRecruitGameOpen && (\n',
    '                    <div className="button-group" style={{ maxHeight: "200px", overflowY: "auto", marginTop: "10px" }}>\n',
    '                      {HOBBY_TAG_GROUPS.flatMap((group) => group.tags).map((tag) => (\n',
    '                        <button\n',
    '                          key={tag}\n',
    '                          type="button"\n',
    '                          className={`button-chip ${selectedRecruitGame === tag ? "selected" : ""}`}\n',
    '                          onClick={() => {\n',
    '                            setSelectedRecruitGame(tag);\n',
    '                            setCustomRecruitGame("");\n',
    '                          }}\n',
    '                        >\n',
    '                          {tag}\n',
    '                        </button>\n',
    '                      ))}\n',
    '                    </div>\n',
    '                  )}\n',
    '                  <input\n',
    '                    value={customRecruitGame}\n',
    '                    onChange={(event) => {\n',
    '                      setCustomRecruitGame(event.target.value);\n',
    '                      setSelectedRecruitGame("");\n',
    '                    }}\n',
    '                    placeholder="リストにない場合はここに入力"\n',
    '                    style={{ marginTop: "10px" }}\n',
    '                  />\n',
    '                </div>\n',
    '                <div style={{ marginTop: "16px", display: "flex", justifyContent: "flex-end" }}>\n',
    '                  <button type="button" onClick={createRecruitment} disabled={loading || users.length === 0}>\n',
    '                    募集を開始\n',
    '                  </button>\n',
    '                </div>\n',
    '              </div>\n',
    '            </div>\n',
]
lines[ui_start:ui_end] = new_ui
path.write_text(''.join(lines))
